//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railways
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Carriages
    {
        public Carriages()
        {
            this.Tickets = new HashSet<Tickets>();
        }

        public int CarriageID { get; set; }
        [Display(Name = "Номер вагона")]
        public int Number { get; set; }
        [Display(Name = "Тип вагона")]
        public int CarriageTypeID { get; set; }
        public int TrainID { get; set; }

        public virtual CarriageTypes CarriageTypes { get; set; }
        public virtual Trains Trains { get; set; }
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
