//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railways
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CarriageTypes
    {
        public CarriageTypes()
        {
            this.Carriages = new HashSet<Carriages>();
        }
    
        public int CarriageTypeID { get; set; }
        [Display(Name = "Тип вагона")]
        public string TypeName { get; set; }
        public int SeatsCount { get; set; }
        public decimal PricePerKm { get; set; }
    
        public virtual ICollection<Carriages> Carriages { get; set; }
    }
}
