//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railways
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Passengers
    {
        public Passengers()
        {
            this.Tickets = new HashSet<Tickets>();
        }

        public int PassengerID { get; set; }
        [Required(ErrorMessage = "Будь ласка, введіть ім'я!")]
        [Display(Name = "Ім'я")]
        public string FirstName { get; set; }
        [Required(ErrorMessage = "Будь ласка, введіть прізвище!")]
        [Display(Name = "Прізвище")]
        public string LastName { get; set; }
        [Display(Name = "Вік")]
        public Nullable<int> Age { get; set; }
        [Display(Name = "Особливі відмітки")]
        public string PassengerStatus { get; set; }

        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
