//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railways
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RailwayTicketOfficeDBEntities1 : DbContext
    {
        public RailwayTicketOfficeDBEntities1()
            : base("name=RailwayTicketOfficeDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carriages> Carriages { get; set; }
        public virtual DbSet<CarriageTypes> CarriageTypes { get; set; }
        public virtual DbSet<Passengers> Passengers { get; set; }
        public virtual DbSet<Routes> Routes { get; set; }
        public virtual DbSet<Stations> Stations { get; set; }
        public virtual DbSet<Tickets> Tickets { get; set; }
        public virtual DbSet<Trains> Trains { get; set; }
    }
}
