//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railways
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Routes
    {
        public int RouteID { get; set; }
        public int StationID { get; set; }
        public int TrainID { get; set; }
        [DataType(DataType.Time)]
        [Display(Name = "Прибуття")]
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        [DataType(DataType.Time)]
        [Display(Name = "Відправлення")]
        public Nullable<System.DateTime> DepartureTime { get; set; }
        [Display(Name = "Км")]
        public int Distance { get; set; }

        public virtual Stations Stations { get; set; }
        public virtual Trains Trains { get; set; }
    }
}
