//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railways
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Stations
    {
        public Stations()
        {
            this.Routes = new HashSet<Routes>();
            this.Tickets = new HashSet<Tickets>();
            this.Tickets1 = new HashSet<Tickets>();
        }

        public int StationID { get; set; }
        [Display(Name = "Назва станції")]
        public string Name { get; set; }

        public virtual ICollection<Routes> Routes { get; set; }
        public virtual ICollection<Tickets> Tickets { get; set; }
        public virtual ICollection<Tickets> Tickets1 { get; set; }
    }
}
