//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railways
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tickets
    {
        public int TicketID { get; set; }
        [Display(Name = "Пасажир")]
        public int PassengerID { get; set; }
        [Display(Name = "Звідки")]
        [Required(ErrorMessage = "Ви дещо забули ввести!")]
        public int StartTrip { get; set; }
        [Display(Name = "Куди")]
        [Required(ErrorMessage = "Ви дещо забули ввести!")]
        public int EndTrip { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Дата")]
        public System.DateTime DateTrip { get; set; }
        [Display(Name = "Поїзд")]
        public int TrainID { get; set; }
        [Display(Name = "Вагон")]
        public int CarriageID { get; set; }
        [Display(Name = "Місце")]
        public int Seat { get; set; }
        [Display(Name = "Вартість")]
        public decimal Price { get; set; }

        public virtual Carriages Carriages { get; set; }
        public virtual Passengers Passengers { get; set; }
        public virtual Stations Stations { get; set; }
        public virtual Stations Stations1 { get; set; }
        public virtual Trains Trains { get; set; }
    }
}
