//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railways
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Trains
    {
        public Trains()
        {
            this.Carriages = new HashSet<Carriages>();
            this.Routes = new HashSet<Routes>();
            this.Tickets = new HashSet<Tickets>();
        }

        public int TrainID { get; set; }
        [Display(Name = "Номер поїзда")]
        public string Number { get; set; }
        [Display(Name = "Маршрут")]
        [Editable(false)]
        public string Route { get; set; }

        public virtual ICollection<Carriages> Carriages { get; set; }
        public virtual ICollection<Routes> Routes { get; set; }
        public virtual ICollection<Tickets> Tickets { get; set; }
    }
}
